"""add created_at to matches

Revision ID: 3671ecb68b26
Revises: 5ea4c1e02226
Create Date: 2026-06-08 16:31:54.827148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3671ecb68b26'
down_revision: Union[str, Sequence[str], None] = '5ea4c1e02226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'created_at')
    # ### end Alembic commands ###
