"""initial schema

Revision ID: 4504e9bc4810
Revises: 
Create Date: 2026-06-07 23:35:05.788138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4504e9bc4810'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('result_entered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=False)
    op.create_table('scoring_rules',
    sa.Column('rule_key', sa.String(length=100), nullable=False),
    sa.Column('rule_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rule_key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('national_id', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('pred_home', sa.Integer(), nullable=False),
    sa.Column('pred_away', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('user_id', 'match_id', name='unique_user_match_prediction')
    )
    op.create_index(op.f('ix_predictions_prediction_id'), 'predictions', ['prediction_id'], unique=False)
    op.create_table('tournament_predictions',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('champion', sa.String(length=100), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_predictions')
    op.drop_index(op.f('ix_predictions_prediction_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('scoring_rules')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('admins')
    # ### end Alembic commands ###
