"""add user score snapshots

Revision ID: 52b20ff59887
Revises: 63df24e0feae
Create Date: 2026-06-20 12:21:36.216993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b20ff59887'
down_revision: Union[str, Sequence[str], None] = '63df24e0feae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_score_snapshots',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_user_score_snapshot_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_score_snapshots')
    # ### end Alembic commands ###
