"""add is_visible to matches

Revision ID: 5ea4c1e02226
Revises: 4504e9bc4810
Create Date: 2026-06-08 14:24:45.360949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea4c1e02226'
down_revision: Union[str, Sequence[str], None] = '4504e9bc4810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admins_admin_id'), 'admins', ['admin_id'], unique=False)
    op.add_column('matches', sa.Column('is_visible', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.create_index(op.f('ix_tournament_predictions_prediction_id'), 'tournament_predictions', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_predictions_prediction_id'), table_name='tournament_predictions')
    op.drop_column('matches', 'is_visible')
    op.drop_index(op.f('ix_admins_admin_id'), table_name='admins')
    # ### end Alembic commands ###
