"""add cascade delete to match relations

Revision ID: bceb7596541e
Revises: 3671ecb68b26
Create Date: 2026-06-08 17:25:40.803692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bceb7596541e'
down_revision: Union[str, Sequence[str], None] = '3671ecb68b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('predictions_match_id_fkey'), 'predictions', type_='foreignkey')
    op.create_foreign_key(None, 'predictions', 'matches', ['match_id'], ['match_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.create_foreign_key(op.f('predictions_match_id_fkey'), 'predictions', 'matches', ['match_id'], ['match_id'])
    # ### end Alembic commands ###
