"""add qualified team fields

Revision ID: f8c0483e714b
Revises: bceb7596541e
Create Date: 2026-06-08 21:58:22.797024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c0483e714b'
down_revision: Union[str, Sequence[str], None] = 'bceb7596541e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('qualified_team', sa.String(length=100), nullable=True))
    op.add_column('predictions', sa.Column('pred_qualified_team', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'pred_qualified_team')
    op.drop_column('matches', 'qualified_team')
    # ### end Alembic commands ###
