
SESSION_LOGGED_IN = "logged_in"

SESSION_USER_ID = "user_id"

SESSION_FIRST_NAME = "first_name"

SESSION_LAST_NAME = "last_name"

SESSION_DEPARTMENT = "department"

SESSION_IS_VERIFIED = "is_verified"

SESSION_MUST_CHANGE_PASSWORD = "must_change_password"

SESSION_NATIONAL_ID = "national_id"

ADMIN_NATIONAL_IDS = [
    "0312322887",
    "0521177766",
    "0021996385"
]

# Scoring system

EXACT_SCORE_POINTS = 12

WINNER_DIFF_POINTS = 8

WINNER_ONLY_POINTS = 4

QUALIFIED_TEAM_POINTS = 3

CHAMPION_POINTS = 40

TOURNAMENT_CHAMPION = None

# 1/8 scoring system
EXACT_SCORE_POINTS = 12

WINNER_DIFF_POINTS = 8

WINNER_ONLY_POINTS = 4

QUALIFIED_TEAM_POINTS = 3